name: Build Clojure app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: install cli sh script
        run: curl -O https://download.clojure.org/install/linux-install-1.11.1.1200.sh

      - name: change mode
        run: chmod +x linux-install-1.11.1.1200.sh

      - name: install cli
        run: sudo ./linux-install-1.11.1.1200.sh

      - name: install rlwrap
        run: sudo apt install rlwrap

      - name: Build app
        run: clj -X:build uber
        env:
          APP_PORT: 8666
